# Project information
site_name: Data Analytics Draft

# Repository
repo_name: Github Repo
repo_url: https://github.com/mmotl/mmotl.github.io

# Theme
theme:
  name: material
  logo: images/logo_cube.png
