# Project information
site_name: Data Analytics Draft

# Repository
repo_name: Github Repo
repo_url: https://github.com/mmotl/mmotl.github.io

# Theme
theme:
  name: material
  # name: readthedocs
  logo: images/logo_cube.png
  font:
    text: Inter
    code: Roboto Mono
  # palette:
  #   - scheme: default
  #     toggle:
  #       icon: material/weather-night
  #       name: Switch to dark mode 
  #   - scheme: slate
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Switch to light mode
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
markdown_extensions:
  - admonition

# Site Navigation
nav:
  - Home: index.md
  - General:
      - How to write Documentation: general/documentation.md